language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: 0JA1+Zo1tAmfvgtmLA8UUnq4GJlY9lOpm9a659k2TRLY+RvM/KhZgxh4JQZD31PGwlOmNM/JopzD78tmOsKAo6LNFTJB7KnVkISwN3PyEuY3hR4/ikaIcrBtYNxH6icKCeWCg6GMDMOghNxVypwoUkiulu5mkOSL0ZLC5CnGEFTOJBPIRe8J0TUE+h4E30dAPPE5SH54wdPIEdGnZNRgblmB/tUP9Auu4KOhpjvBwxbc6FVLwNIZPn7DQ8V0M4C2IbMj62cMDtRUEjLRGdoBQgNGaIgjsFkuraJPLkMWDQnhJaqQx6Q6fn952Ki+AWQCSOVUboI5hBi16jG2QZ6tY6qJH/HTiw/QXuouDz0Ipe25M4lsE26w0IFjxM7MqfIh92xAQ389LU9P6eNnKezhHgSyct/xV3b0vpIwM+f4W+bIW50cahI+QQA1qknk5s93EP4Z2ZRD5+oisjyHm5jocm3jEph4ZunVl2PCR2ewjb+CItPbzcqvkgY0dqG9eXL/3yJXtA8UJNE1qwgp8PmrlounozUDkzufvOHEz8z0iY6tHUC3kHPiyeDmig0J+fo7UTy5KSCqqu0bwI2zwf+Cm+jvwoG8i0PwmTp3CARP/mIjkgnoAf8f3z2QtrsMDk0cxitwv5kuo5sG0g327TFBH4oun+3/vzIn74CRtE0Fs+Y
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"

