language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: tspp07k1pX7BMf0K5IxXr+5h3B9+0MgW5q2ZqctrbU/fg+r/wYt2ljnU50fhvLOCTQfrH2ysk/mXFmTpmiPLlYl7IheLy/WWGfqUOU2GDj40Cb0TyI2Q3n6PL7t9JooBae7J/VElmNsMSPz/ERoZOfxrSWWuYTLsBxB6rv/pQKP2l8ogQwuMusNuqytVNGuTqvbbup3nkN0X3fmiHLCjXJDHNos/im7Rc7rSBxK1bUbjW6EnTqONy+BhEDAsUhq4Ce4Nf4wudCtFALyr0bdt+fxaHfTWjqxEyaRzTyCioyrvPrRS9yL7LZH1KpNg+SgIF4xpDWOqSHChCXkQrzbTlxCxp8HjNfHZrehAYQekCgLdPPz5bYCZfzptLQS4VHvGhl8J7cAB+uugrr3cwK3hnDI1dR/FnnPKmmmj/psmJCtan2V9YLSVmARKxY4yhkGjxQKUAtaTK7K7Sz5N/xxXA+Ad/n/MFbU+3F+zLh4CDMEFMsJ4a/vjGgahFEDItSRD+yzwIeCZhjbdW1wwYWCKHMqByIlmYfrxBk1wpD3XCIcb13VT2NuGg6Q/m+GFg6bWJuQHmqUZoUxf9ad740JvfAZNhKfu+nCIgssArz7hxC6PY09uyzguylQNGdSDryBoVlg7pznS/mB0LDSawVOZy2Esbfg2WDEtqoF5fsdZBIw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"

